// AUTO-GENERATED by scripts/build-manifest.mjs — do not edit by hand.
// Regenerate with: pnpm manifest
import type { CourseManifest } from "./course.js";

export const COURSE_MANIFEST: CourseManifest = {
  "weeks": [
    {
      "week": 1,
      "theme": "homecoming",
      "month": 1,
      "lessons": [
        {
          "slug": "week-01/puppy-proofing",
          "week": 1,
          "order": 1,
          "title": "puppy-proofing & the safe space",
          "minutesPerDay": 15,
          "body": "Before the cuddles: get on your hands and knees and see the house the way a four-pound puppy does. Loose cords look like chew toys. A dropped ibuprofen is an emergency. A gap behind the couch is a den.\n\nSet up one \"safe zone\" — an exercise pen or gated corner with his bed, a water bowl, and two chew toys. This is where Biru lives when nobody can actively watch him. It's not a punishment; it's how you prevent bad habits from ever being rehearsed.\n\nRotate his toys so novelty stays high, and keep one \"jackpot\" chew for the pen only, so the pen predicts good things.\n\n⚠️ **biewer tip:** biewers are small enough to squeeze into gaps you'd never suspect — behind appliances, under recliners. Block anything wider than your fist, and treat recliner chairs as off-limits forever.",
          "tasks": [
            {
              "id": "week-01/puppy-proofing/task-1",
              "text": "Get down to Biru's eye level and remove every cord, cable, and chewable hazard from his zone"
            },
            {
              "id": "week-01/puppy-proofing/task-2",
              "text": "Set up a pen or gated area with his bed, water, and two safe chew toys"
            },
            {
              "id": "week-01/puppy-proofing/task-3",
              "text": "Stash anything swallowable (hair ties, coins, socks) out of reach in every room he'll visit"
            }
          ]
        },
        {
          "slug": "week-01/crate-introduction",
          "week": 1,
          "order": 2,
          "title": "crate introduction",
          "minutesPerDay": 10,
          "body": "The crate is Biru's bedroom, never his jail. Start with the door open and make it rain: toss a treat in, let him walk in, eat, walk out. Repeat until he's diving in happily.\n\nNext, feed his meals in there. Then start closing the door for just a few seconds while he's eating, opening it before he cares. Build up slowly — seconds, then a minute, then a few.\n\nNever open the door while he's crying (that teaches \"crying opens doors\"). Wait for two seconds of quiet, then open calmly. And never use the crate as punishment — it must always predict good things.\n\n⚠️ **biewer tip:** toy breeds get cold easily. Line the crate with a fleece blanket and keep it out of drafts — a cozy crate is half the battle for a biewer.",
          "tasks": [
            {
              "id": "week-01/crate-introduction/task-1",
              "text": "Biru walks into the crate on his own to get a tossed treat"
            },
            {
              "id": "week-01/crate-introduction/task-2",
              "text": "He eats a full meal inside the crate with the door open"
            },
            {
              "id": "week-01/crate-introduction/task-3",
              "text": "He stays relaxed inside with the door closed for 30 seconds while you sit nearby"
            }
          ]
        },
        {
          "slug": "week-01/potty-routine-v1",
          "week": 1,
          "order": 3,
          "title": "potty routine v1 — the schedule",
          "minutesPerDay": 15,
          "body": "Here's the truth about biewers: their bladder is the size of a walnut. Potty training a toy breed is famously slow — not because they're dumb (they're not), but because they physically cannot hold it long. The fix is a schedule so strict it feels silly.\n\nTake him out: right after waking, right after eating or drinking, right after play, and every 1–2 hours in between. Go to the same spot, stand there boring as a lamppost, and the instant he finishes — party. Treat within two seconds, praise, the works.\n\nMisses are YOUR misses (too long between trips). Never punish an accident; just clean with enzyme cleaner so the smell doesn't invite a repeat.\n\n⚠️ **biewer tip:** in rain or cold a biewer may simply refuse to go outside. Have a backup indoor potty pad in a fixed spot from day one — many biewer owners keep both systems for life.",
          "tasks": [
            {
              "id": "week-01/potty-routine-v1/task-1",
              "text": "Written potty schedule is on the fridge and both humans are following it"
            },
            {
              "id": "week-01/potty-routine-v1/task-2",
              "text": "Biru is taken out within 5 minutes of waking, eating, drinking, and playing"
            },
            {
              "id": "week-01/potty-routine-v1/task-3",
              "text": "Three successful outdoor potties rewarded with a treat + party within 2 seconds"
            },
            {
              "id": "week-01/potty-routine-v1/task-4",
              "text": "One full day with every potty trip logged (successes and misses)"
            }
          ]
        },
        {
          "slug": "week-01/first-night",
          "week": 1,
          "order": 4,
          "title": "first night survival",
          "minutesPerDay": 5,
          "body": "The first nights are the hardest — for both of you. Biru just left his mom and littermates; some crying is grief, not manipulation. Put the crate right next to your bed so he can hear you breathe. A ticking clock or a warm (not hot) wrapped heat pack mimics littermates.\n\nDo a final potty trip right before lights out. If he cries at 2am, he probably genuinely needs to go — carry him out, no talking, no play, potty, straight back in the crate. Boring is the message: night is for sleeping.\n\nIt gets better fast. Most puppies settle within a week when the routine never wavers.\n\n⚠️ **biewer tip:** a biewer puppy this tiny can't make it through the night at 10 weeks — expect one 2–3am potty run for the first couple of weeks. It's temporary. Truly.",
          "tasks": [
            {
              "id": "week-01/first-night/task-1",
              "text": "Crate is next to your bed where Biru can see and smell you"
            },
            {
              "id": "week-01/first-night/task-2",
              "text": "A 10pm final potty trip and calm wind-down routine happened"
            },
            {
              "id": "week-01/first-night/task-3",
              "text": "You survived one night taking him out (calmly, boringly) when he genuinely needed it"
            }
          ]
        }
      ]
    },
    {
      "week": 2,
      "theme": "trust & name",
      "month": 1,
      "lessons": [
        {
          "slug": "week-02/name-recognition",
          "week": 2,
          "order": 1,
          "title": "name recognition",
          "minutesPerDay": 5,
          "body": "\"Biru\" should be the best word in the world. Say his name once in a happy voice; the instant he looks at you, mark it (\"yes!\") and treat. That's the whole game — name means look at me, and looking at me pays.\n\nTen reps per session, a few sessions a day, always with something great at the end. Never use his name for scoldings, baths, or nail trims in these early weeks — you're building an unbreakable \"name = good\" association that recall will ride on later.\n\nIf he doesn't look, don't repeat \"Biru Biru BIRU\" — you'll teach him the name means nothing. Get closer, get more exciting, try again.\n\n⚠️ **biewer tip:** biewers are sensitive to tone. A sharp or annoyed voice can make this breed shut down entirely — keep the name-game voice light and silly, always.",
          "tasks": [
            {
              "id": "week-02/name-recognition/task-1",
              "text": "Biru whips his head around when you say \"Biru\" from 3 feet away"
            },
            {
              "id": "week-02/name-recognition/task-2",
              "text": "He responds to his name from across the room"
            },
            {
              "id": "week-02/name-recognition/task-3",
              "text": "He responds to his name while mildly distracted (sniffing something interesting)"
            }
          ]
        },
        {
          "slug": "week-02/hand-feeding",
          "week": 2,
          "order": 2,
          "title": "hand-feeding & bonding",
          "minutesPerDay": 10,
          "body": "For a few meals this week, skip the bowl. Feed Biru his kibble piece by piece from your hand — sometimes for nothing, sometimes for a glance at you, sometimes sprinkled while you handle a paw.\n\nThis does three quiet, powerful things: it makes human hands the source of all good things (never something to guard against), it teaches a soft mouth (if teeth touch skin, say \"ouch,\" pause three seconds, continue), and it builds focus on your face that every future cue depends on.\n\nSplit the job between both of you. Biru should conclude that *both* his humans are treat vending machines with great taste.\n\n⚠️ **biewer tip:** a biewer's daily food ration is tiny — hand-feeding real meals means you get 60+ training reps a day without adding a single extra calorie.",
          "tasks": [
            {
              "id": "week-02/hand-feeding/task-1",
              "text": "One full meal fed piece-by-piece from your hand"
            },
            {
              "id": "week-02/hand-feeding/task-2",
              "text": "Your wife/partner also hand-fed a full meal (the bond is with both of you)"
            },
            {
              "id": "week-02/hand-feeding/task-3",
              "text": "Biru takes food gently, no tooth contact, thanks to the 'ouch + pause' rule"
            }
          ]
        },
        {
          "slug": "week-02/handling-basics",
          "week": 2,
          "order": 3,
          "title": "handling paws, ears & mouth",
          "minutesPerDay": 5,
          "body": "Biewers need lifelong grooming — brushing, nail trims, teeth cleaning, face wiping. A dog who panics at being handled makes every one of those a wrestling match for the next 15 years. So we start now, absurdly gently.\n\nTouch a paw. Treat. Touch an ear. Treat. Lift a lip. Treat. One second each, always followed by food, always stopping while he's still relaxed. You're not grooming anything yet — you're teaching \"hands on my body predict cheese.\"\n\nWatch his body: loose and wiggly means continue, stiff or head-turning means you went too fast. Shrink the touch, raise the pay.\n\n⚠️ **biewer tip:** the face is the sensitive zone — biewers need daily eye-area wiping to prevent tear staining, so put extra reps into gentle face touches this week.",
          "tasks": [
            {
              "id": "week-02/handling-basics/task-1",
              "text": "Touched each paw for one second each, treat after every touch, Biru stayed relaxed"
            },
            {
              "id": "week-02/handling-basics/task-2",
              "text": "Lifted his lip and briefly touched his ear, treat after each"
            },
            {
              "id": "week-02/handling-basics/task-3",
              "text": "Held one paw gently for 3 full seconds while he stayed loose and wiggly"
            }
          ]
        },
        {
          "slug": "week-02/brushing-habit",
          "week": 2,
          "order": 4,
          "title": "the daily brushing habit",
          "minutesPerDay": 5,
          "body": "That silky biewer coat is hair, not fur — it grows long, it tangles, and it mats close to the skin where you can't see. The only defense is a short daily brushing habit, and the only way that habit is pleasant is if you build it now, while he's a baby.\n\nShow the brush → treat. One stroke → treat. Two strokes → treat. Keep sessions to two minutes and end while he's still happy — a hundred short good sessions beat one long bad one.\n\nUse a pin brush for the body and learn the \"line brushing\" idea: part the hair, brush from the skin out, section by section. Right now the coat is short and easy; the habit is what you're grooming.\n\n⚠️ **biewer tip:** always mist the coat lightly with water or conditioner spray before brushing — dry-brushing a biewer coat breaks the hair and actually creates tangles.",
          "tasks": [
            {
              "id": "week-02/brushing-habit/task-1",
              "text": "Showed Biru the brush, treated, did one single stroke, treated"
            },
            {
              "id": "week-02/brushing-habit/task-2",
              "text": "Did a 2-minute brushing session with treats every few strokes"
            },
            {
              "id": "week-02/brushing-habit/task-3",
              "text": "Brushed him on 3 different days this week, ending before he got squirmy"
            }
          ]
        }
      ]
    },
    {
      "week": 3,
      "theme": "potty & bite",
      "month": 1,
      "lessons": [
        {
          "slug": "week-03/potty-routine-v2",
          "week": 3,
          "order": 1,
          "title": "potty routine v2 — the accident protocol",
          "minutesPerDay": 10,
          "body": "By now the schedule is running. This week is about the misses — because there will be misses, and how you handle them decides how fast this finishes.\n\nIf you catch him mid-squat: a cheerful \"outside!\", scoop him up, finish outdoors, treat like it was his idea. If you find a puddle after the fact: say nothing, clean it with enzyme cleaner, and quietly note that he was unsupervised too long. Punishment after the fact teaches exactly one thing — hide from the humans when you need to pee. That's the opposite of what you want.\n\nStart learning his \"tell\": the sudden sniffing spiral, the drift toward a corner. Catching the tell is graduation-level potty training.\n\n⚠️ **biewer tip:** small dogs have small accidents that are easy to miss under furniture — do a nose-level sweep of his zone daily, because every undiscovered accident invites a repeat visit.",
          "tasks": [
            {
              "id": "week-03/potty-routine-v2/task-1",
              "text": "Two accident-free days in a row on the schedule"
            },
            {
              "id": "week-03/potty-routine-v2/task-2",
              "text": "Every accident this week was cleaned with enzyme cleaner, zero scolding"
            },
            {
              "id": "week-03/potty-routine-v2/task-3",
              "text": "You caught Biru's pre-potty 'tell' (circling, sniffing) and got him out in time twice"
            }
          ]
        },
        {
          "slug": "week-03/bite-inhibition",
          "week": 3,
          "order": 2,
          "title": "bite inhibition",
          "minutesPerDay": 10,
          "body": "Puppy teeth are needles and Biru will use them — on hands, ankles, and the drawstrings of your favorite hoodie. This is normal and important: right now he's learning how much jaw pressure is too much, and the only teacher available is you.\n\nWhen teeth hit skin too hard: a calm \"ouch,\" then all fun stops for three seconds. No yelling, no pushing (pushing is a game). Then offer a toy — \"that, not me.\" If he keeps coming back hard, calmly end the play session entirely.\n\nThe goal isn't zero mouthing yet; it's a progressively softer mouth. Full \"no teeth on humans\" comes as adult teeth arrive.\n\n⚠️ **biewer tip:** never play rough with hands with a toy breed — what's cute at 4 pounds becomes a bite-risk habit in a dog whose warning nips can still break skin. Toys are for teeth; hands are for petting.",
          "tasks": [
            {
              "id": "week-03/bite-inhibition/task-1",
              "text": "Used \"ouch + 3-second pause\" consistently for every hard nip today"
            },
            {
              "id": "week-03/bite-inhibition/task-2",
              "text": "Mouthing got noticeably softer across the week (log it — you will forget)"
            },
            {
              "id": "week-03/bite-inhibition/task-3",
              "text": "Redirected to a toy within 2 seconds on 5 separate chomp attempts"
            }
          ]
        },
        {
          "slug": "week-03/chew-redirection",
          "week": 3,
          "order": 3,
          "title": "chew-toy redirection",
          "minutesPerDay": 5,
          "body": "Teething is coming, and Biru's gums are going to ache. He *will* chew — the only question is what. Your job is to make the right answer the easy answer.\n\nKeep three approved chews with different textures (rubber, soft rope, a puppy-safe teething chew) in every room he uses. When he gnaws a chair leg or a shoe: no drama. Trade him — offer the toy, praise madly when he takes it. Chasing him for the stolen sock is the best game he's ever invented; a boring trade beats it every time.\n\nFrozen wet washcloth twists are teething gold. So are frozen carrots (tiny ones, supervised).\n\n⚠️ **biewer tip:** size chews for a tiny jaw — anything harder than a fingernail-press can crack toy-breed teeth. Skip antlers and hard nylon entirely.",
          "tasks": [
            {
              "id": "week-03/chew-redirection/task-1",
              "text": "Three approved chews of different textures are always within Biru's reach"
            },
            {
              "id": "week-03/chew-redirection/task-2",
              "text": "Every 'wrong chew' this week got a calm trade for a better toy (no chasing, no yelling)"
            },
            {
              "id": "week-03/chew-redirection/task-3",
              "text": "Biru chose an approved chew on his own at least twice (celebrate it!)"
            }
          ]
        },
        {
          "slug": "week-03/alone-time-seconds",
          "week": 3,
          "order": 4,
          "title": "alone time — seconds to minutes",
          "minutesPerDay": 10,
          "body": "Here is the week-3 secret nobody tells you: separation anxiety is easier to prevent than cure, and prevention starts when being alone is measured in *seconds*.\n\nPop Biru in his pen with something great — a stuffed food toy is perfect — and simply walk out of the room. Ten seconds. Come back before he fusses. No announcement when you leave, no party when you return; comings and goings should be the most boring events in his day.\n\nStretch it gradually: 30 seconds, a minute, two, while you do normal things nearby. He's learning the deepest lesson of his little life: *humans leave, humans always come back, and meanwhile I have snacks.*\n\n⚠️ **biewer tip:** biewers are true velcro dogs — bred for companionship and prone to shadowing you to the bathroom. Skipping this lesson is the #1 regret of toy-breed owners. Do the reps.",
          "tasks": [
            {
              "id": "week-03/alone-time-seconds/task-1",
              "text": "Stepped out of sight for 10 seconds and returned before any fussing, 5 reps"
            },
            {
              "id": "week-03/alone-time-seconds/task-2",
              "text": "Biru stayed calm in his pen with a stuffed food toy while you were in another room for 2 minutes"
            },
            {
              "id": "week-03/alone-time-seconds/task-3",
              "text": "Practiced 'leaving is boring': no goodbye speeches, no excited reunions"
            }
          ]
        }
      ]
    },
    {
      "week": 4,
      "theme": "social butterfly",
      "month": 1,
      "lessons": [
        {
          "slug": "week-04/socialization-checklist",
          "week": 4,
          "order": 1,
          "title": "the socialization checklist",
          "minutesPerDay": 15,
          "body": "Right now — roughly weeks 8 to 14 of his life — Biru's brain is running a once-in-a-lifetime program: *things I meet calmly now are normal forever; things I never meet become scary later.* This window closes. Use it.\n\nThe recipe is exposure + distance + cheese. Let him see, hear, or sniff a new thing from far enough away that he's curious rather than worried, feed a stream of tiny treats, leave while it's still going well. He does not need to interact with everything — calmly observing the garbage truck *is* the win.\n\nAim for a handful of new experiences a day, always at his pace. If he startles, add distance, add treats, and shrink the exposure. Never flood him.\n\n⚠️ **biewer tip:** the world is enormous when you're four pounds. Let Biru observe scary-big things from your arms first — height is confidence for a toy breed — then work down to the ground.",
          "tasks": [
            {
              "id": "week-04/socialization-checklist/task-1",
              "text": "Biru calmly experienced 5 new sounds this week (vacuum, doorbell, umbrella, traffic, blender) paired with treats"
            },
            {
              "id": "week-04/socialization-checklist/task-2",
              "text": "He walked on 3 new surfaces (grass, tile, metal grate / bath mat)"
            },
            {
              "id": "week-04/socialization-checklist/task-3",
              "text": "He watched 5 new types of people from a comfy distance (hats, beards, kids, bikes, wheelchairs) and got paid for it"
            }
          ]
        },
        {
          "slug": "week-04/meeting-dogs",
          "week": 4,
          "order": 2,
          "title": "meeting other dogs (safely)",
          "minutesPerDay": 15,
          "body": "Dog friends matter, but for a biewer puppy the *quality* of early dog meetings beats quantity by a mile. One bad scare from a bouncy labrador can install a lifetime of leash reactivity.\n\nChoose his classmates: calm adult dogs you know are vaccinated and gentle, ideally small or famously tolerant. Keep first greetings to three seconds — sniff, sniff, \"let's go!\", treat, done. Short and sweet, ending while everyone still wants more.\n\nLearn his overwhelm signals: tail tucked, hiding behind your legs, lip licking, trying to leave. When you see them, calmly scoop him up and create distance. You are his bodyguard; being rescued *builds* confidence, it doesn't ruin it.\n\n⚠️ **biewer tip:** skip the open dog park for at least a year (many biewer owners skip it forever). A 4-pound dog in a big-dog scrum is genuinely unsafe — curated playdates only.",
          "tasks": [
            {
              "id": "week-04/meeting-dogs/task-1",
              "text": "Biru met 2 calm, vaccinated, small-or-gentle dogs in a controlled space"
            },
            {
              "id": "week-04/meeting-dogs/task-2",
              "text": "Every greeting was 3 seconds, then happy retreat and treat — no marathon wrestling"
            },
            {
              "id": "week-04/meeting-dogs/task-3",
              "text": "You watched his body language and rescued him the moment he looked overwhelmed"
            }
          ]
        },
        {
          "slug": "week-04/car-rides",
          "week": 4,
          "order": 3,
          "title": "car rides",
          "minutesPerDay": 10,
          "body": "If the only place the car ever goes is the vet, Biru will do the math. Beat him to it: make the car a treat dispenser that occasionally drives somewhere wonderful.\n\nStart parked. Carrier in, treats in, engine off, hang out, done. Next: engine on, no driving. Then a five-minute loop that ends at a park or a friend's house. You're stacking the deck so \"car\" predicts adventure.\n\nHe rides in a crash-tested carrier or dog car seat, secured with the seatbelt, every single time — never loose, never on a lap. Loose four-pound dogs and airbags are a horrifying combination.\n\n⚠️ **biewer tip:** small dogs get motion-sick more easily. Keep pre-drive meals light, crack a window for airflow, and if he drools or gulps, shorten the drives and build back up.",
          "tasks": [
            {
              "id": "week-04/car-rides/task-1",
              "text": "Biru sat in his (secured) car carrier in the driveway, engine off, having treats — twice"
            },
            {
              "id": "week-04/car-rides/task-2",
              "text": "One 5-minute drive that ended somewhere fun (not the vet)"
            },
            {
              "id": "week-04/car-rides/task-3",
              "text": "One 15-minute drive with calm behavior the whole way"
            }
          ]
        },
        {
          "slug": "week-04/sit",
          "week": 4,
          "order": 4,
          "title": "sit",
          "minutesPerDay": 5,
          "body": "The classic, and Biru is ready. Hold a treat to his nose, lift it slowly up and back over his head — as the nose goes up, the butt goes down. The moment it touches: \"yes!\", treat, party.\n\nAfter a dozen smooth lure reps, get the treat out of your hand: same hand motion, empty hand, treat from the other hand. Then add the word — say \"sit,\" pause a beat, then the hand signal. Soon the word alone works.\n\nStart cashing it in immediately: sit for the food bowl, sit for the leash, sit for the door. \"Sit\" becomes his way of saying *please* — a dog who knows how to ask politely rarely needs to demand rudely.\n\n⚠️ **biewer tip:** don't push his rear down, ever — a biewer puppy's joints are delicate, and hands-on molding teaches nothing anyway. Let the lure do the work.",
          "tasks": [
            {
              "id": "week-04/sit/task-1",
              "text": "Biru follows a treat lure up-and-back into a sit, 5 for 5"
            },
            {
              "id": "week-04/sit/task-2",
              "text": "He sits on the verbal cue \"sit\" alone, no lure, 4 out of 5 times"
            },
            {
              "id": "week-04/sit/task-3",
              "text": "He sits politely (instead of jumping) for his food bowl"
            }
          ]
        }
      ]
    },
    {
      "week": 5,
      "theme": "leash — tiny dog edition",
      "month": 2,
      "lessons": [
        {
          "slug": "week-05/harness-fitting",
          "week": 5,
          "order": 1,
          "title": "harness, not collar",
          "minutesPerDay": 5,
          "body": "Rule one of walking a biewer: the leash never, ever attaches to a neck collar. A toy breed's trachea is soft and tiny; one hard lunge against a collar can cause real damage. Collars are for ID tags. Walks happen on a harness.\n\nChoose a Y-front step-in or vest harness sized for toy breeds. Fitting: snug enough that two fingers slide under, loose enough that nothing rubs behind his front legs.\n\nThen sell it to him: harness appears → treats appear. Head through the loop → treat. Clip → treat → immediately off. Build up to him wearing it around the house while great things happen. A dog who dives *into* his harness makes every walk for the next 15 years easier.\n\n⚠️ **biewer tip:** that silky coat mats under harness straps — brush the armpit and chest areas after every wear, and take the harness off at home.",
          "tasks": [
            {
              "id": "week-05/harness-fitting/task-1",
              "text": "A Y-front harness fits: snug enough for two fingers, no rubbing behind the legs"
            },
            {
              "id": "week-05/harness-fitting/task-2",
              "text": "Harness goes on = treats rain down; Biru stops wiggling within 3 sessions"
            },
            {
              "id": "week-05/harness-fitting/task-3",
              "text": "He wore the harness around the house for 10 happy minutes"
            }
          ]
        },
        {
          "slug": "week-05/indoor-leash",
          "week": 5,
          "order": 2,
          "title": "leash walking — living room edition",
          "minutesPerDay": 10,
          "body": "First leash lessons happen where it's boring: your living room. Clip the lightest leash you can find to the harness and just let him drag it around (supervised — leashes snag). It's furniture now, not news.\n\nThen pick it up and become interesting: pat your leg, shuffle backward, treat him every time he arrives at your ankle. Twenty steps of \"hanging out near the human on a loose leash\" is the entire foundation of every good walk.\n\nNever drag him. If he plants, you've lost his brain — get closer, get happier, lower the bar. The leash is a safety line, not a steering wheel.\n\n⚠️ **biewer tip:** buy the lightest leash made — a heavy clip alone weighs on a 4-pound puppy's harness like a barbell and teaches him the leash is a burden.",
          "tasks": [
            {
              "id": "week-05/indoor-leash/task-1",
              "text": "Biru dragged the light leash around the house (supervised) with zero drama"
            },
            {
              "id": "week-05/indoor-leash/task-2",
              "text": "He followed you around the living room on a loose leash for 20 steps, treats at your ankle"
            },
            {
              "id": "week-05/indoor-leash/task-3",
              "text": "Zero leash pulling from YOU — no dragging him anywhere, ever"
            }
          ]
        },
        {
          "slug": "week-05/first-walks",
          "week": 5,
          "order": 3,
          "title": "first real walks outside",
          "minutesPerDay": 15,
          "body": "The first outdoor walks are not exercise — they're field trips. The goal is a puppy who thinks *outside* is wonderful, not a puppy who covers distance.\n\nKeep it short (ten minutes is plenty at this age) and let him sniff. Sniffing is how dogs read the newspaper; a walk that's all march and no sniff is like being dragged through a library too fast to read.\n\nBring the best treats and pay generously for check-ins — every time he glances at you unprompted, \"yes!\" and treat. You're planting the seed that walks are a *together* activity. If he freezes or won't take food, he's overwhelmed: pick him up, go home, try a quieter street tomorrow.\n\n⚠️ **biewer tip:** watch the ground temperature and the weather — a biewer gets cold fast and hot pavement burns tiny paws in seconds. In winter, a sweater isn't fashion; it's function.",
          "tasks": [
            {
              "id": "week-05/first-walks/task-1",
              "text": "Two 10-minute 'sniff walks' where Biru set the pace and direction (mostly)"
            },
            {
              "id": "week-05/first-walks/task-2",
              "text": "He kept taking treats outdoors (if he can't eat, he's over threshold — go closer to home)"
            },
            {
              "id": "week-05/first-walks/task-3",
              "text": "One walk included 30 seconds of just sitting on a bench watching the world"
            }
          ]
        },
        {
          "slug": "week-05/loose-leash-foundations",
          "week": 5,
          "order": 4,
          "title": "loose-leash foundations",
          "minutesPerDay": 10,
          "body": "Here's the deal you're offering Biru: *a loose leash makes the world move; a tight leash makes the world stop.* Enforce it with the patience of a saint and it becomes physics to him.\n\nThe moment the leash tightens: stop walking. Just stand there, boring. The instant it softens — even because he turned to see why you stopped — \"yes!\", walk on. That's it. That's the whole technique. It feels slow for three days and then suddenly you have a dog who self-corrects.\n\nMeanwhile, make your left ankle the best real estate on the street: random treats delivered right at the seam of your shoe. Dogs hang out where the vending machine is.\n\n⚠️ **biewer tip:** a biewer pulling on a harness looks harmless — resist the urge to just let it slide. A 4-pound puller becomes a leash-tangling, ankle-orbiting chaos machine. The rules are the rules, even for cute.",
          "tasks": [
            {
              "id": "week-05/loose-leash-foundations/task-1",
              "text": "Ten reps of \"leash goes tight → you stop → leash softens → walk resumes\""
            },
            {
              "id": "week-05/loose-leash-foundations/task-2",
              "text": "Biru walked 20 steps beside you outdoors on a J-shaped loose leash"
            },
            {
              "id": "week-05/loose-leash-foundations/task-3",
              "text": "You paid him at your left ankle so often he started defaulting there"
            }
          ]
        }
      ]
    },
    {
      "week": 6,
      "theme": "core cues",
      "month": 2,
      "lessons": [
        {
          "slug": "week-06/down",
          "week": 6,
          "order": 1,
          "title": "down",
          "minutesPerDay": 10,
          "body": "From a sit, hold a treat to Biru's nose and slowly lower it straight down to the floor between his paws, then drag it slightly forward — nose follows, elbows fold, down. \"Yes!\", release the treat while he's still lying down.\n\nSmall dogs often find \"down\" harder than big dogs — it's a vulnerable position when everything in the world towers over you. Train it on a comfy mat, never on cold slick floors, and keep your body language soft.\n\nFade the lure the same way as sit: real motion with empty hand, pay from the other hand, then word first, signal second. Downs are the gateway to \"stay,\" \"settle at the café,\" and \"go chill on your mat\" — worth polishing.\n\n⚠️ **biewer tip:** if he pops back up instantly, you're paying too late — deliver the treat between his front paws *while* his belly is on the mat, so down is where the money lands.",
          "tasks": [
            {
              "id": "week-06/down/task-1",
              "text": "Lured Biru from sit into a down with a treat to the floor, 5 for 5"
            },
            {
              "id": "week-06/down/task-2",
              "text": "He goes down on hand signal alone (no food in the lure hand)"
            },
            {
              "id": "week-06/down/task-3",
              "text": "He responds to the verbal \"down\" alone, 4 out of 5 times"
            }
          ]
        },
        {
          "slug": "week-06/stay-v1",
          "week": 6,
          "order": 2,
          "title": "stay — version 1",
          "minutesPerDay": 10,
          "body": "Stay is really three separate skills — duration, distance, distraction — and the classic mistake is training all three at once. This week: duration only, tiny doses.\n\nCue sit, hold a flat \"wait\" palm, count one-mississippi, \"yes!\", treat, release word (\"free!\"). That's a rep. Build seconds slowly: 2, 4, 6, 8. If he breaks, no drama — you asked for too much; make it easier.\n\nTwo rules that matter: pay *during* the stay (bring the treat to him), and always end with your release word so *he* never decides when stays end. Distance comes next week-ish: one step back, return, pay. One step is a big deal when your dog is four pounds and you're a skyscraper.\n\n⚠️ **biewer tip:** keep stay sessions to 2–3 minutes max. A biewer's focus tank is small and runs on premium fuel — quit while he's brilliant.",
          "tasks": [
            {
              "id": "week-06/stay-v1/task-1",
              "text": "Biru holds a sit-stay for 5 seconds with you standing right in front, 5 for 5"
            },
            {
              "id": "week-06/stay-v1/task-2",
              "text": "He holds a stay while you take one step back and return"
            },
            {
              "id": "week-06/stay-v1/task-3",
              "text": "He holds a stay while you shift your weight or raise your arms (distraction-proofing lite)"
            }
          ]
        },
        {
          "slug": "week-06/recall-foundations",
          "week": 6,
          "order": 3,
          "title": "recall foundations (indoors)",
          "minutesPerDay": 10,
          "body": "Recall is the cue that can save Biru's life, and it's built on one iron law: *coming when called is ALWAYS the best deal available.* No exceptions, no fine print, forever.\n\nIndoors, six feet away: \"Biru, come!\" in your happiest voice, open arms, maybe a little run-away-from-him (chasing you is irresistible). When he arrives: jackpot — three treats, one at a time, plus a party. Grab his harness gently *then* treat sometimes, so hand-reaching-for-harness never becomes the end of fun.\n\nPlay recall ping-pong with your wife: call him back and forth across the apartment, both of you paying like slot machines. Never call him for anything he hates (nail trims, crate-and-leave) — go get him for those instead.\n\n⚠️ **biewer tip:** biewers read enthusiasm like a lie detector. A flat, bored \"come\" gets a flat, bored response — commit to the silly voice. Your dignity was already gone the day you started narrating his poops.",
          "tasks": [
            {
              "id": "week-06/recall-foundations/task-1",
              "text": "20 reps of \"Biru, come!\" → sprint → jackpot party, across the living room"
            },
            {
              "id": "week-06/recall-foundations/task-2",
              "text": "Recall ping-pong between both humans, 10 rounds, both paying big"
            },
            {
              "id": "week-06/recall-foundations/task-3",
              "text": "He came away from a mild distraction (a toy on the floor) for the recall word"
            }
          ]
        },
        {
          "slug": "week-06/touch-targeting",
          "week": 6,
          "order": 4,
          "title": "\"touch\" — nose targeting",
          "minutesPerDay": 5,
          "body": "\"Touch\" — Biru bops his nose into your flat palm — looks like a party trick, but it's a Swiss army knife. It repositions him without picking him up, ends jumping (nose to palm beats paws on legs), redirects him past scary things on walks, and later powers fancy tricks.\n\nHold your flat palm two inches from his nose. Dogs investigate — the moment his nose touches, \"yes!\", treat from the other hand. He'll figure out the game embarrassingly fast; biewers are sharp.\n\nAdd the word once he's reliable, then make it mobile: palm a step away, palm low, palm leading him onto the scale at the vet. A dog with a strong \"touch\" can be steered anywhere, cheerfully.\n\n⚠️ **biewer tip:** being constantly picked up and plopped places is the toy-dog experience — \"touch\" gives Biru a way to move himself, and dogs with agency are calmer, more confident dogs.",
          "tasks": [
            {
              "id": "week-06/touch-targeting/task-1",
              "text": "Biru boops your flat palm with his nose on the cue \"touch,\" 8 out of 10"
            },
            {
              "id": "week-06/touch-targeting/task-2",
              "text": "He follows the moving palm — target held low leads him a few steps"
            },
            {
              "id": "week-06/touch-targeting/task-3",
              "text": "You used \"touch\" to reposition him once instead of picking him up"
            }
          ]
        }
      ]
    },
    {
      "week": 7,
      "theme": "impulse control",
      "month": 2,
      "lessons": [
        {
          "slug": "week-07/leave-it-1",
          "week": 7,
          "order": 1,
          "title": "\"leave it\" — level 1",
          "minutesPerDay": 10,
          "body": "Close a boring treat in your fist and offer it. Biru will lick, paw, and nibble at your knuckles — say nothing, do nothing, be a statue. The instant he gives up and pulls back, even a centimeter: \"yes!\" and pay him a *better* treat from your other hand.\n\nHe is learning the most counterintuitive lesson in dog school: *backing off the thing gets you the thing (or better).* Never feed him the treat he was mugging — the prize always comes from elsewhere, so the \"leave it\" treat stays theoretical.\n\nOnce he backs off fast, wait for the bonus: that little glance up at your face. Pay that glance like a jackpot. \"When in doubt, check in with my human\" is the entire philosophy of a well-trained dog, in one look.\n\n⚠️ **biewer tip:** use rice-grain-sized treats and keep sessions under 5 minutes — a biewer's daily calorie budget is about that of a hamster with ambitions.",
          "tasks": [
            {
              "id": "week-07/leave-it-1/task-1",
              "text": "Biru ignores a treat in your closed fist for 3 seconds (he stops mugging your hand)"
            },
            {
              "id": "week-07/leave-it-1/task-2",
              "text": "He backs off the fist and looks at YOU instead — the magic moment"
            },
            {
              "id": "week-07/leave-it-1/task-3",
              "text": "5-for-5 reps where looking away earns a better treat from the other hand"
            }
          ]
        },
        {
          "slug": "week-07/drop-it",
          "week": 7,
          "order": 2,
          "title": "\"drop it\"",
          "minutesPerDay": 10,
          "body": "\"Drop it\" is \"leave it\"'s sibling: leave-it is *don't pick it up*, drop-it is *spit out what's already in the mouth*. With a curious ground-level vacuum like a biewer, you need both.\n\nStart as a trade, not a theft. He has a toy; you present a treat at his nose; the toy falls out (physics — can't chew and sniff simultaneously); \"drop it,\" treat, and here's the crucial part: *give the toy back* most of the time. Drop-it that usually means \"brief pause, then double prize\" builds a dog who spits things out happily. Drop-it that means \"you lose your stuff\" builds a dog who swallows evidence and runs.\n\nNever chase, never pry his mouth open unless it's a true emergency — both teach him to gulp faster next time.\n\n⚠️ **biewer tip:** a biewer's mouth is small but determined — chicken bones on the sidewalk are the classic city hazard. Drill drop-it *before* week 10's café outings, not after the first incident.",
          "tasks": [
            {
              "id": "week-07/drop-it/task-1",
              "text": "Traded Biru a toy for a treat 10 times — toy given BACK most times (drop ≠ lose)"
            },
            {
              "id": "week-07/drop-it/task-2",
              "text": "He spits out a mid-value item on the verbal \"drop it\" alone"
            },
            {
              "id": "week-07/drop-it/task-3",
              "text": "Emergency practice: he dropped something while you stayed calm (no chasing, no grabbing)"
            }
          ]
        },
        {
          "slug": "week-07/leave-it-2",
          "week": 7,
          "order": 3,
          "title": "\"leave it\" — level 2",
          "minutesPerDay": 10,
          "body": "Level up. Place a treat on the floor and cover it with your flat hand. Say \"leave it\" once. When he stops trying to excavate your palm and pulls back — \"yes!\", pay from the other hand. Progress to hovering your hand an inch above the treat, then to a fully uncovered treat with your hand ready to cover it if he dives.\n\nThen make it real: \"accidentally\" drop a piece of kibble while making dinner. \"Leave it.\" The floor food scenario is the one that actually matters — that's where the dropped grape, the medication, the mystery chicken bone will appear one day.\n\nMove the game to different rooms; dogs don't generalize automatically, and a leave-it that only works in the kitchen is a kitchen decoration.\n\n⚠️ **biewer tip:** keep sessions under 5 minutes with rice-grain treats — impulse control is genuinely *tiring* for a puppy brain, and a fried biewer gets zoomies, not wisdom.",
          "tasks": [
            {
              "id": "week-07/leave-it-2/task-1",
              "text": "Biru ignores a treat under your open, flat hand"
            },
            {
              "id": "week-07/leave-it-2/task-2",
              "text": "Treat on the floor, uncovered — he holds back on one \"leave it\" cue"
            },
            {
              "id": "week-07/leave-it-2/task-3",
              "text": "It works with a dropped piece of kibble during dinner prep"
            },
            {
              "id": "week-07/leave-it-2/task-4",
              "text": "Practiced in 2 different rooms"
            }
          ]
        },
        {
          "slug": "week-07/doorway-manners",
          "week": 7,
          "order": 4,
          "title": "doorway & food-bowl manners",
          "minutesPerDay": 10,
          "body": "Impulse control graduates from party games to daily life this week. Two rituals, practiced at every natural opportunity:\n\n**The bowl.** Ask for a sit. Lower the bowl. If his butt lifts, the bowl silently rises again — no scolding, the bowl simply obeys gravity in reverse. When he holds the sit until the bowl lands: \"free!\", dinner is served. Three days of consistency and he'll sit for dinner like it's his idea.\n\n**The door.** Doors are where tiny dogs get stepped on and where dashers are born. At every interior door: \"wait,\" door opens a crack, closes if he surges, opens again. You step through first, then \"free!\". This isn't dominance theater — it's a safety habit that one day stops him at an open front door with a street beyond it.\n\n⚠️ **biewer tip:** underfoot is the most dangerous place a biewer lives. A dog who defaults to *sit and wait* at doors and kitchen counters is a dog who doesn't get accidentally punted.",
          "tasks": [
            {
              "id": "week-07/doorway-manners/task-1",
              "text": "Biru holds a sit while the food bowl lowers — bowl goes back up if he breaks, 5 clean reps"
            },
            {
              "id": "week-07/doorway-manners/task-2",
              "text": "He waits at an open interior door until \"free!\" (you step through first)"
            },
            {
              "id": "week-07/doorway-manners/task-3",
              "text": "One full mealtime and one real doorway, manners intact, no reminders"
            }
          ]
        }
      ]
    },
    {
      "week": 8,
      "theme": "home alone",
      "month": 2,
      "lessons": [
        {
          "slug": "week-08/departure-cues",
          "week": 8,
          "order": 1,
          "title": "departure-cue desensitization",
          "minutesPerDay": 10,
          "body": "Dogs are pattern-reading machines. Keys jingle → coat goes on → human vanishes: by now Biru has the sequence memorized, and for a velcro breed each step can crank the anxiety dial before you've even left.\n\nSo scramble the data. Pick up your keys and... sit back down. Put on shoes and... make tea. Touch the doorknob and... wander off. Ten meaningless repetitions a day and the cues stop predicting abandonment; they stop predicting anything at all.\n\nWatch him during reps: perked ears and pacing mean the cue still has power — repeat it until boredom wins. This is dull homework that pays off enormously.\n\n⚠️ **biewer tip:** biewers track their humans with their eyes constantly. If he's already shadowing you room-to-room all day, add \"closed bathroom door\" practice too — the mildest possible separation, many times a day.",
          "tasks": [
            {
              "id": "week-08/departure-cues/task-1",
              "text": "Picked up keys / put on shoes 10 times today and went... nowhere. Biru stopped reacting"
            },
            {
              "id": "week-08/departure-cues/task-2",
              "text": "Did the full fake-leaving routine (coat, keys, door touch) with zero drama"
            },
            {
              "id": "week-08/departure-cues/task-3",
              "text": "Biru stayed relaxed on his mat through 3 fake departures in a row"
            }
          ]
        },
        {
          "slug": "week-08/alone-15-30",
          "week": 8,
          "order": 2,
          "title": "15–30 minutes truly alone",
          "minutesPerDay": 15,
          "body": "Time for real departures — short, boring, and verified. Set up his pen with a frozen stuffed food toy (the good stuff, alone-time exclusive). Leave without ceremony. Stand outside the door for five minutes. Come back in like it's nothing.\n\nThe critical tool here is a camera — an old phone on a shelf works. You need to *see* what alone-Biru does, because \"he seemed fine\" and \"he cried for 14 straight minutes\" look identical from outside a door. Calm chewing, wandering, napping: extend the time. Continuous crying, pacing, door-scratching: shrink the time and rebuild slower.\n\nGrow the intervals across the week: 5, 10, 15, 20, 30. Always return before panic, always low-key on both ends.\n\n⚠️ **biewer tip:** a stuffed toy sized for toy breeds takes a biewer 20+ minutes to finish — it's not a snack, it's a babysitter. Freeze three at a time so one's always ready.",
          "tasks": [
            {
              "id": "week-08/alone-15-30/task-1",
              "text": "Biru stayed calm and busy (stuffed toy) for 5 real minutes with you outside the front door"
            },
            {
              "id": "week-08/alone-15-30/task-2",
              "text": "15 minutes fully alone — verified calm on a phone camera, not just hoped"
            },
            {
              "id": "week-08/alone-15-30/task-3",
              "text": "30 minutes alone with relaxed behavior: chewing, napping, zero continuous crying"
            }
          ]
        },
        {
          "slug": "week-08/barking-management",
          "week": 8,
          "order": 3,
          "title": "barking management",
          "minutesPerDay": 10,
          "body": "Biewers have opinions and a surprisingly big voice for a small chassis. Some barking is legitimate (someone's at the door!) — the goal isn't a silent dog, it's a dog with an off switch.\n\nFirst, audit: what actually sets him off? Window traffic, hallway footsteps, the doorbell? For window sentries, manage the view (frosted film on the bottom pane is magic). For the doorbell, run the drill: bell rings → treats scatter on his mat → bell *predicts mat snacks*, not intruder panic.\n\nFor opinion-barking: acknowledge once (\"thank you\"), redirect to his mat, and pay the quiet — never yell, which reads as you joining the bark chorus. Reward silence generously; barking that stops working goes extinct.\n\n⚠️ **biewer tip:** small-dog barking gets laughed off until it's a doorbell meltdown at year three. Take it as seriously as you would from a german shepherd — the training is identical, just cuter.",
          "tasks": [
            {
              "id": "week-08/barking-management/task-1",
              "text": "You can name Biru's top 3 bark triggers (window? doorbell? hallway sounds?)"
            },
            {
              "id": "week-08/barking-management/task-2",
              "text": "\"Thank you, done\" protocol used consistently: acknowledge, redirect to mat, pay quiet"
            },
            {
              "id": "week-08/barking-management/task-3",
              "text": "Doorbell drill: bell rings, Biru gets treats on his mat, 5 reps"
            }
          ]
        },
        {
          "slug": "week-08/crate-happy-place",
          "week": 8,
          "order": 4,
          "title": "crate as happy place — proofing",
          "minutesPerDay": 10,
          "body": "Week one built the crate; this week finishes it into what it should be for life: Biru's own room, chosen voluntarily.\n\nAdd the cue: \"bedtime\" (or whatever you like), toss nothing, and wait — he knows this game. Pay when he enters, pay extra when he settles. Practice closed-door time *while you're home and visible*: dinner on the couch, him in the crate with a chew, ten calm minutes. Crating must not only predict departures, or it becomes a departure alarm.\n\nThe graduation signal costs you nothing to spot: one day you'll look over and find he's put himself to bed in the open crate. When that happens, the crate has stopped being furniture and become his address.\n\n⚠️ **biewer tip:** biewers nest — add a soft blanket he can burrow into and you'll double the crate's pull. Wash it rarely (his smell is the point) and never as punishment cleanup.",
          "tasks": [
            {
              "id": "week-08/crate-happy-place/task-1",
              "text": "Biru trots into his crate on the cue \"bedtime\" without a lure"
            },
            {
              "id": "week-08/crate-happy-place/task-2",
              "text": "He settles in the crate with the door closed for 10 minutes while you watch TV in the room"
            },
            {
              "id": "week-08/crate-happy-place/task-3",
              "text": "He napped in the open crate BY CHOICE at least once this week (the true victory)"
            }
          ]
        }
      ]
    },
    {
      "week": 9,
      "theme": "recall for real",
      "month": 3,
      "lessons": [
        {
          "slug": "week-09/long-line",
          "week": 9,
          "order": 1,
          "title": "long-line outdoors",
          "minutesPerDay": 15,
          "body": "Recall moves outside this week, and outside is where recalls go to die: squirrels, smells, other dogs, wind. The bridge between living-room hero and off-leash dog is the long line — 15 feet of light lead that lets him range while physics guarantees he can't fail beyond arm's reach.\n\nQuiet park, low distractions. Let him drift and sniff, then hit him with your best \"Biru, come!\" — and here's the discipline: *only call when you'd bet money on it.* If he's mid-sniff on something fascinating, wait. Every ignored recall teaches him the word is optional; every successful one, jackpot-paid, hardens it into reflex.\n\nIf he doesn't come, don't repeat the cue — gently reel the line while sweet-talking, then pay anyway, then lower the difficulty.\n\n⚠️ **biewer tip:** clip the long line to the *harness*, never a collar — a full-tilt biewer hitting the end of 15 feet on his neck is exactly the trachea injury we've been avoiding all course.",
          "tasks": [
            {
              "id": "week-09/long-line/task-1",
              "text": "Biru dragged a 15-foot long line in a quiet park while you practiced 5 easy recalls"
            },
            {
              "id": "week-09/long-line/task-2",
              "text": "Every single recall today was paid with a jackpot — outdoor rates are triple indoor rates"
            },
            {
              "id": "week-09/long-line/task-3",
              "text": "Zero recall failures — because you only called when you would have bet $20 on him coming"
            }
          ]
        },
        {
          "slug": "week-09/recall-with-distractions",
          "week": 9,
          "order": 2,
          "title": "recall with distractions",
          "minutesPerDay": 15,
          "body": "Time to run the gauntlet. On the long line, deliberately practice recalls *away from* increasingly interesting things: first a fascinating bush, then a passing stranger, then a distant dog. Each success gets the triple-jackpot and — this is sneaky and important — *often gets released right back to the fun*: \"come!\" → party → \"go sniff!\". Recall that ends fun kills recall; recall that's a toll booth on the way back to fun gets paid happily forever.\n\nRank his distraction hierarchy honestly. For most biewers: smells < strangers < dogs < that one specific enemy pigeon. Work up the ladder; skipping rungs teaches failure.\n\nBy the end of the week you want one unplanned, real-world recall under your belt — the moment you realize the button actually works.\n\n⚠️ **biewer tip:** other dogs are usually a biewer's #1 distraction — they're social little gremlins. Buy extra distance from dog-distractions at first; success at 40 feet builds the recall that later works at 10.",
          "tasks": [
            {
              "id": "week-09/recall-with-distractions/task-1",
              "text": "Recall away from a mild distraction (interesting smell) on the long line, 5 for 5"
            },
            {
              "id": "week-09/recall-with-distractions/task-2",
              "text": "Recall away from a medium distraction (person walking past, distant dog)"
            },
            {
              "id": "week-09/recall-with-distractions/task-3",
              "text": "One \"real world\" recall you didn't plan — and you paid like he saved your life"
            }
          ]
        },
        {
          "slug": "week-09/emergency-recall",
          "week": 9,
          "order": 3,
          "title": "the emergency recall word",
          "minutesPerDay": 5,
          "body": "Your normal recall will be great. But build one more layer: an *emergency* word, reserved for the once-a-year moment a door blows open onto a busy street. It works because it's never diluted — no casual use, no unpaid reps, no \"eh, good enough\" rewards.\n\nPick something you'd never say otherwise — \"PARTY!\", \"JACKPOT!\", the sillier the better. Charging it is pure Pavlov: say the word, then immediately deliver the best food that exists in your house (real chicken, cheese, the forbidden stuff). Ten reps over a few days. He doesn't have to *do* anything yet; the word just predicts miracles.\n\nThen test cold, once: from another room, out of nowhere. Thunderpaws incoming = it's loaded. Re-charge with a few reps monthly, forever, and guard it like the fire extinguisher it is.\n\n⚠️ **biewer tip:** a biewer bolting is genuinely hard to grab — they're low, fast, and dodge like rabbits. The emergency word that makes him *run at you* beats every lunge-and-grab you'll ever attempt.",
          "tasks": [
            {
              "id": "week-09/emergency-recall/task-1",
              "text": "Picked a unique word (\"PARTY!\"?) — never used in daily chatter, sounds distinct at a distance"
            },
            {
              "id": "week-09/emergency-recall/task-2",
              "text": "Charged it 10 times: word → chicken rains from the sky, no behavior required yet"
            },
            {
              "id": "week-09/emergency-recall/task-3",
              "text": "Cold-tested once from another room: he came running like the floor was lava"
            }
          ]
        },
        {
          "slug": "week-09/off-leash-enclosed",
          "week": 9,
          "order": 4,
          "title": "off-leash in enclosed spaces",
          "minutesPerDay": 15,
          "body": "The training-wheels-off moment — in a fully fenced space. Rent-a-yard apps (Sniffspot), a friend's fenced garden, or an empty tennis court all work. Walk the fence line first: a biewer-sized dog fits through biewer-sized gaps, and \"enclosed\" means enclosed *for four pounds*, not for a labrador.\n\nThen unclip and let him be a dog. Your only jobs: pay every voluntary check-in (he wanders near you unprompted — treat! this is the behavior that makes off-leash dogs safe), and sprinkle in a handful of recalls at moments you'd bet on, each one paid and released back to play.\n\nWhat you're watching for is the invisible leash: a dog who orbits, checks in, and treats you as home base. That orbit is what you've actually been building for nine weeks.\n\n⚠️ **biewer tip:** keep him leashed anywhere birds of prey are common if he's under 5 pounds — hawks genuinely assess toy dogs. Open rural fields are big-dog territory; enclosed urban spaces are your friend.",
          "tasks": [
            {
              "id": "week-09/off-leash-enclosed/task-1",
              "text": "Found a truly enclosed space (fenced yard, sniffspot, empty tennis court) and checked the fence line"
            },
            {
              "id": "week-09/off-leash-enclosed/task-2",
              "text": "Full off-leash session with 5 paid recalls mixed into free play"
            },
            {
              "id": "week-09/off-leash-enclosed/task-3",
              "text": "He \"checked in\" voluntarily (came near without being called) at least 3 times — each one paid"
            }
          ]
        }
      ]
    },
    {
      "week": 10,
      "theme": "city dog",
      "month": 3,
      "lessons": [
        {
          "slug": "week-10/polite-greetings",
          "week": 10,
          "order": 1,
          "title": "polite greetings with people",
          "minutesPerDay": 10,
          "body": "Here is the toy-dog trap: Biru is so cute that strangers will *reward his worst behavior*. Jumping, spinning, demanding — \"aww, it's fine, he's tiny!\" It is not fine; it's how adorable puppies become obnoxious adults.\n\nThe rule is four on the floor: paws down (or better, a sit) is the only position that earns petting. When admirers approach — and with a biewer, they will — you become the bouncer: \"He's in training! Give him a second to sit first.\" Most people love helping. If someone swoops anyway and he jumps, calmly step back with him and reset.\n\nAt home, same rules apply to guests: Biru on leash for arrivals, sit earns hellos, jumping makes visitors turn into boring statues (brief your friends — they're training equipment now).\n\n⚠️ **biewer tip:** looming over a tiny dog is scary — teach greeters to crouch sideways and offer a hand low, rather than reaching down over his head like a claw machine.",
          "tasks": [
            {
              "id": "week-10/polite-greetings/task-1",
              "text": "\"Four on the floor\" enforced: admirers may only pet when Biru's paws are down"
            },
            {
              "id": "week-10/polite-greetings/task-2",
              "text": "You coached 3 strangers through the correct greeting (\"please wait until he sits\")"
            },
            {
              "id": "week-10/polite-greetings/task-3",
              "text": "Biru offered a sit to greet someone without being asked — jackpot moment"
            }
          ]
        },
        {
          "slug": "week-10/dog-greetings",
          "week": 10,
          "order": 2,
          "title": "dog-dog greetings on leash",
          "minutesPerDay": 10,
          "body": "On-leash greetings are dog etiquette on hard mode — leashes trap dogs in face-to-face meetings they'd never choose. Keep them rare, short, and curated.\n\nProtocol: ask the other owner first (\"is your dog friendly with small dogs?\" — note the specific question). If yes, approach in an arc rather than head-on, allow three seconds of sniffing, then a cheery \"let's go!\" and a treat for disengaging. Ending greetings *before* things get weird is the whole skill.\n\nBetter than face-greetings entirely: the parallel walk. Two dogs walking the same direction ten feet apart, gradually closer, no forced meeting. It's how dog friendships actually form, and it's the safest structure for a 4-pound participant.\n\n⚠️ **biewer tip:** \"he's friendly!\" shouted from thirty feet, attached to a charging retriever, is not a greeting — it's an incoming event. Step off the path, pick Biru up if needed, zero shame. You're his advocate, not the neighborhood's manners police.",
          "tasks": [
            {
              "id": "week-10/dog-greetings/task-1",
              "text": "3-second greeting rule followed with 2 different dogs: sniff, sniff, \"let's go!\", treat"
            },
            {
              "id": "week-10/dog-greetings/task-2",
              "text": "You asked \"is your dog friendly?\" BEFORE every approach — and skipped the sketchy ones"
            },
            {
              "id": "week-10/dog-greetings/task-3",
              "text": "One successful parallel walk with another dog (the best kind of dog socializing)"
            }
          ]
        },
        {
          "slug": "week-10/cafe-settle",
          "week": 10,
          "order": 3,
          "title": "café settle — chill in public",
          "minutesPerDay": 15,
          "body": "The final boss of city-dog skills: doing absolutely nothing, in public, on purpose. A dog who can settle under a café table opens up your whole life — brunches, patios, travel.\n\nBuild it at home on a distinct travel mat: \"go to your mat\" → lure onto it → down → slow trickle of treats *for staying put*. The mat becomes a treat-generating magic carpet. Extend the calm: treats every few seconds, then every 30, then only occasionally, while you sit beside him scrolling your phone (authentic training conditions).\n\nThen take the show on the road, ramping difficulty: quiet bench → slow coffee shop patio at off-hours → real brunch. Bring the mat, a chew, and low expectations. Fifteen calm minutes is a triumph; leave before he unravels.\n\n⚠️ **biewer tip:** under-the-table beats on-your-lap for learning settle — lap dogs stay on alert scanning the room from the best vantage point. Down on the mat, world muffled by tablecloth, biewers actually nap.",
          "tasks": [
            {
              "id": "week-10/cafe-settle/task-1",
              "text": "\"Go to your mat\" is fluent at home: he trots to the travel mat and lies down on cue"
            },
            {
              "id": "week-10/cafe-settle/task-2",
              "text": "One 15-minute practice settle somewhere mild (a quiet bench, a friend's porch)"
            },
            {
              "id": "week-10/cafe-settle/task-3",
              "text": "One real café/patio outing where Biru settled on his mat under the table — the dream, achieved"
            }
          ]
        },
        {
          "slug": "week-10/city-noises",
          "week": 10,
          "order": 4,
          "title": "elevators, streets & city noises",
          "minutesPerDay": 10,
          "body": "City life is a sensory assault at ankle height: buses hiss, grates clang, elevators do whatever elevators do. This week you methodically make each one boring, using the same recipe as week 4 — distance + treats + retreat while it's going well.\n\nElevators: ride with him in your arms first (height = confidence), treats flowing, then a ride with paws on the floor. Loud streets: find the distance where he notices trucks but still takes food, feed through each rumble, and creep closer over days — never all at once.\n\nKeep a running list of his \"haunted objects\" (every dog has some — a flapping awning, a specific statue) and give each one the treatment: approach at his pace, pay generously, never force contact.\n\n⚠️ **biewer tip:** sidewalk grates are genuinely dangerous for biewer-sized paws, not just scary — teach him to walk around them (guide with the leash, pay the detour) rather than over them, as a lifelong habit.",
          "tasks": [
            {
              "id": "week-10/city-noises/task-1",
              "text": "Elevator ride (in arms, then on floor) paired with treats — no trembling by rep 3"
            },
            {
              "id": "week-10/city-noises/task-2",
              "text": "Stood at a manageable distance from a loud street, fed treats through 3 bus/truck passes"
            },
            {
              "id": "week-10/city-noises/task-3",
              "text": "One new \"city surface\" conquered: grate, metal stairs, revolving-door lobby (carried is fine!)"
            }
          ]
        }
      ]
    },
    {
      "week": 11,
      "theme": "cooperative care",
      "month": 3,
      "lessons": [
        {
          "slug": "week-11/nail-trims",
          "week": 11,
          "order": 1,
          "title": "nail trims without drama",
          "minutesPerDay": 5,
          "body": "Nail trims sit at the intersection of week 2's handling work and pure patience. The secret is decoupling every step: clippers visible ≠ clipping. Clippers touching nail ≠ clipping. One clip ≠ ten clips.\n\nSequence, one step per session if needed: clippers appear → treat. Clippers touch a nail → treat. Clip the very tip of ONE nail → jackpot, session over. One nail a day is a completely legitimate schedule forever — that's a full rotation every two weeks, which is exactly right.\n\nTake only the tips (biewer nails have a quick that's easy to hit) and keep styptic powder nearby for confidence — yours, mostly. If either of you gets tense, stop; tomorrow is another nail.\n\n⚠️ **biewer tip:** biewers often tolerate a nail *grinder* better than clippers — no sudden pressure-crack sensation. Introduce it with the same one-step-at-a-time recipe: sound on = treats, from across the room first.",
          "tasks": [
            {
              "id": "week-11/nail-trims/task-1",
              "text": "Clipper appears → treats appear, 10 reps — Biru now looks happy to see clippers"
            },
            {
              "id": "week-11/nail-trims/task-2",
              "text": "Clipped ONE nail, jackpot, walked away — three days in a row"
            },
            {
              "id": "week-11/nail-trims/task-3",
              "text": "Did a full paw (5 nails) in one calm session, ending before he cared"
            }
          ]
        },
        {
          "slug": "week-11/teeth-brushing",
          "week": 11,
          "order": 2,
          "title": "teeth brushing",
          "minutesPerDay": 5,
          "body": "Unglamorous but critical: toy breeds have the worst teeth in the dog world. Crowded jaws, plaque that turns to disease fast, and dental extractions as a common middle-age event — unless someone brushes. That someone is you, and daily beats weekly by a mile.\n\nMake it a dessert course, not a procedure. Dog toothpaste (poultry flavor — never human toothpaste) licked off your finger for a few days. Then your finger, paste-loaded, rubbed on the front teeth for five seconds. Then a finger-brush, then a tiny toothbrush, adding seconds and teeth gradually. Front teeth and canines are easy; back molars are the goal but come last.\n\nAnchor it to a daily event — after the evening potty trip, before the bedtime cue — and it becomes automatic for you both.\n\n⚠️ **biewer tip:** at his adult weight, dental disease can cost a biewer actual years of life — vets consistently name it the #1 preventable toy-breed health issue. This boring little lesson is quietly the most important one in month three.",
          "tasks": [
            {
              "id": "week-11/teeth-brushing/task-1",
              "text": "Biru licks dog toothpaste off your finger like it's dessert, 3 days running"
            },
            {
              "id": "week-11/teeth-brushing/task-2",
              "text": "Finger-brush rubbed on his front teeth for 5 seconds, treat, done"
            },
            {
              "id": "week-11/teeth-brushing/task-3",
              "text": "A real (tiny) toothbrush did his front teeth and canines in one calm session"
            }
          ]
        },
        {
          "slug": "week-11/topknot-tolerance",
          "week": 11,
          "order": 3,
          "title": "topknot & face care",
          "minutesPerDay": 5,
          "body": "The biewer signature look — hair up, face visible, maximum drama — isn't just aesthetics. Hair in the eyes causes irritation and tear staining, so face care and the topknot are health routines wearing a cute disguise.\n\nDaily face wiping first: soft damp cloth at the inner eye corners, one gentle swipe, treat. This prevents the rust-colored tear stains that plague white-faced breeds and keeps his eyes comfortable.\n\nThe topknot: gather → hold three seconds → release → treat, many reps, before any band appears. First real topknot: loose, small band (never rubber — snag city), five minutes, then removed *by you* before he paws it out. Gradually extend. If he learns pawing removes it, you'll fight that forever, so always beat him to the removal.\n\n⚠️ **biewer tip:** band tension matters — too tight pulls the skin and *creates* the face-scratching you're trying to avoid. You should be able to slide a fingertip under the band's base easily.",
          "tasks": [
            {
              "id": "week-11/topknot-tolerance/task-1",
              "text": "Face wiped (eye corners) with a damp cloth daily this week, treats flowing"
            },
            {
              "id": "week-11/topknot-tolerance/task-2",
              "text": "Hair gathered on top of his head, held 3 seconds, released, treat — 10 reps"
            },
            {
              "id": "week-11/topknot-tolerance/task-3",
              "text": "A real topknot (small band) stayed in for 5 minutes without a pawing meltdown"
            }
          ]
        },
        {
          "slug": "week-11/groomer-prep",
          "week": 11,
          "order": 4,
          "title": "groomer prep & the spa visit",
          "minutesPerDay": 10,
          "body": "Sometime soon a professional will bathe, dry, and trim Biru — and whether that's a spa day or a trauma depends mostly on this week's prep.\n\nHome rehearsal first: the full fake groom. Brush, handle every paw, wipe the face, and — the weird one — practice standing on a raised non-slip surface (counter with a bath mat) since grooming happens on tables. Pay throughout.\n\nThen the genius move: the hello-only visit. Walk into the groomer's, staff hand out treats, Biru sniffs the scary-smelling place, everyone leaves. No groom. The shop stops predicting doom. First real appointment: keep it minimal (bath, tidy, nails) and brief the groomer that he's a first-timer — good groomers slow down for that.\n\n⚠️ **biewer tip:** the blow dryer is the #1 grooming fear for small dogs. Desensitize at home: your hairdryer on cool + low, pointed *near* not at him, treats raining — a dog who's met wind before makes the groomer's day.",
          "tasks": [
            {
              "id": "week-11/groomer-prep/task-1",
              "text": "Ran a \"fake groom\" at home: brush, paw handling, face wipe, standing on a table/counter with treats"
            },
            {
              "id": "week-11/groomer-prep/task-2",
              "text": "Visited the groomer for a happy hello-only visit: treats from staff, zero grooming, left"
            },
            {
              "id": "week-11/groomer-prep/task-3",
              "text": "First real (short!) groom appointment booked or completed — bath + tidy, nothing dramatic"
            }
          ]
        }
      ]
    },
    {
      "week": 12,
      "theme": "graduation",
      "month": 3,
      "lessons": [
        {
          "slug": "week-12/trick-spin-paw",
          "week": 12,
          "order": 1,
          "title": "tricks — spin & shake paws",
          "minutesPerDay": 10,
          "body": "Welcome to dessert. Tricks are pure fun — but they're also disguised training gold: they sharpen his lure-following, deepen his love of sessions, and (research-backed truth) mental work tires a dog out better than an extra walk.\n\n**Spin:** treat at nose height, draw a slow horizontal circle; he follows; \"yes!\" as he completes it. Shrink the lure to a finger twirl, add \"spin!\". Train both directions — dogs have a handedness, and one way will be comically harder.\n\n**Shake:** hold a treat in a closed fist at chest height; when he paws at it (he will), catch the paw gently, \"yes!\", treat. Name it once reliable. The double bill of spin-then-shake is a guaranteed crowd-pleaser and takes about four days total.\n\n⚠️ **biewer tip:** biewers are natural performers with a flair for drama — they learn tricks fast and *remember applause*. Your wife's delighted reaction is a genuine training reward; deploy her strategically.",
          "tasks": [
            {
              "id": "week-12/trick-spin-paw/task-1",
              "text": "Biru follows a lure in a full circle: \"spin!\" — both directions attempted, one is fluent"
            },
            {
              "id": "week-12/trick-spin-paw/task-2",
              "text": "\"Shake\" — he lifts a paw into your waiting hand on cue"
            },
            {
              "id": "week-12/trick-spin-paw/task-3",
              "text": "Performed both for an audience member (wife counts, delighted screaming encouraged)"
            }
          ]
        },
        {
          "slug": "week-12/trick-roll-beg",
          "week": 12,
          "order": 2,
          "title": "tricks — roll over & sit pretty",
          "minutesPerDay": 10,
          "body": "Two showstoppers. **Roll over:** from a down, lure the treat from his nose toward his shoulder blade — head follows, body tips onto one hip, keep the lure moving in an arc and momentum does the rest. Pay generously at the halfway point (on his side) for the first days; rolling belly-up is a trust exercise, and rushing it backfires.\n\n**Sit pretty** (beg): from a sit, raise a treat just above his nose — front paws leave the ground, mark instantly at first, even for a half-second lift. Build the hold time slowly; it's a genuine core workout and strength takes weeks to develop. Let him balance against your arm at first if he wants.\n\nThese two are patience tricks — a rep or two a day beats drilling. You have the rest of his life to perfect them.\n\n⚠️ **biewer tip:** sit pretty is actually *great* physio for small dogs (core and back strength) — but only in tiny doses while he's a puppy. Three reps a session max until he's past a year old.",
          "tasks": [
            {
              "id": "week-12/trick-roll-beg/task-1",
              "text": "Lured Biru from down → shoulder → full roll over, treat mid-roll for courage"
            },
            {
              "id": "week-12/trick-roll-beg/task-2",
              "text": "\"Roll over\" works from the verbal + a small hand circle"
            },
            {
              "id": "week-12/trick-roll-beg/task-3",
              "text": "\"Sit pretty\" (beg) held for 2 seconds with a straight back — core strength takes weeks, patience"
            }
          ]
        },
        {
          "slug": "week-12/skills-assessment",
          "week": 12,
          "order": 3,
          "title": "the full skills assessment",
          "minutesPerDay": 20,
          "body": "Exam day — but the friendly kind. Run through the whole curriculum cold, one cue each, real-world conditions, and grade honestly: **pass / wobbly / needs work.**\n\nThe dirty dozen: name response · sit · down · stay (10 seconds) · come (indoors) · come (outdoors, long line) · leave it (floor treat) · drop it · loose leash (one block) · crate on cue · settle on mat (5 minutes) · alone 30 minutes.\n\nWobbly is normal — a 6-month-old puppy is a teenager with a learner's permit, not a finished dog. Tune up the wobblies with one short session each. \"Needs work\" items just become next month's practice list; training doesn't end at graduation, it just stops having a syllabus.\n\nThen write his report card in the diary. You'll reread it in a year and cry a little. This is by design.\n\n⚠️ **biewer tip:** adolescence (6–12 months) will temporarily *un-train* several of these — recall especially. This is neurology, not defiance. Keep paying well and hold the line; the trained adult dog re-emerges around his first birthday.",
          "tasks": [
            {
              "id": "week-12/skills-assessment/task-1",
              "text": "The written checklist: run all 12 core skills cold, one attempt each, note pass/wobbly/needs-work"
            },
            {
              "id": "week-12/skills-assessment/task-2",
              "text": "Every \"wobbly\" skill got one tune-up session this week"
            },
            {
              "id": "week-12/skills-assessment/task-3",
              "text": "You wrote Biru a report card comment in the diary (be honest, be kind, be funny)"
            }
          ]
        },
        {
          "slug": "week-12/graduation-day",
          "week": 12,
          "order": 4,
          "title": "graduation day 🎓",
          "minutesPerDay": 15,
          "body": "Twelve weeks. From a four-pound stranger who cried at 2am to a dog who sits at doorways, comes when called, and naps under café tables. Take a second and feel that.\n\nToday has three official duties, none skippable. **The photo:** graduation attire (a bow tie counts; a tiny mortarboard earns extra credit), best light in the apartment, forty attempts to get one where he's looking at the camera. **The celebration:** his favorite everything — the good walk, the sanctioned puppuccino, a brand-new toy he gets to destroy. **The diary entry:** title it \"graduation day,\" attach the photo, and write a few lines to the two of you who'll read it when he's grey around the muzzle.\n\nWhat's next? Everything. Adolescence (hold the line), advanced tricks, maybe therapy-dog work — biewers excel at it. But that's next quarter's syllabus. Today, you celebrate.\n\n⚠️ **biewer tip:** biewers live 12–16 years. The habits you built these twelve weeks — the brushing, the teeth, the training games, the diary — are the ones you'll still be doing in 2040. You didn't just train a puppy; you built a life together. Class dismissed. 🎓",
          "tasks": [
            {
              "id": "week-12/graduation-day/task-1",
              "text": "The graduation photo: Biru in a bow tie / tiny cap (this is mandatory and you know it)"
            },
            {
              "id": "week-12/graduation-day/task-2",
              "text": "A celebratory outing: his favorite walk, a puppuccino, a new toy — the works"
            },
            {
              "id": "week-12/graduation-day/task-3",
              "text": "A diary entry titled \"graduation day\" with the photo and a note to future you both"
            }
          ]
        }
      ]
    }
  ],
  "totalLessons": 48,
  "totalTasks": 146
} as CourseManifest;
